#This file is part of the SportResultsAnalyzer package.
#(c) Alexander Lukashevich <aleksandr.dwt@gmail.com>
#For the full copyright and license information, please view the LICENSE file that was distributed with this source code.

version: '3.3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash -c '
      [ ! -d 'node_modules' ] && npm install ;
      service tor start &
      polipo socksParentProxy=localhost:9050 &
      npm start
      '"
#    command: bash -c 'sleep 10000'
    environment:
      - NODE_ENV=production
      - SITE_URL
      - PASSWORD
      - OFFICE1_SITE
      - OFFICE2_SITE
      - OFFICE3_SITE
    volumes:
      - ./app:/usr/src/app
    ports:
      - 80:80

  mongodb:
      image: mongo:latest
      volumes:
        - dbdata:/data/db
      ports:
          - 27017:27017

volumes:
  dbdata: