module.exports = {
    sports: {
        basketball:  {
            urls: [
                {id: '8', urls:['/', '/', '/']},
            ],
            archive: [
                {id: '6302r'},
                {id: '6320r'},
                {id: '6430r'},
                {id: '6289r'},
                {id: '6293r'},
                {id: '6230r'},
            ],
        },
        soccer: {
            urls: [
                {id: '63', urls:['/v3/ru/line/bets/period=0;chmp=a:1324;', '/su/betting/Football/Portugal/Primeira+Liga/', '/sport/futbol/portugalija-primejjra-liga']},
                {id: '100', urls:['/', '/su/betting/Football/Portugal/Segunda+Liga/', '/']},
                {id: '216', urls:['/v3/ru/line/bets/period=0;chmp=a:11168;', '/su/betting/Football/Saudi+Arabia/Pro+League/', '/sport/futbol/saudovskaja-aravija-pro-liga']},
                {id: '19', urls:['/v3/ru/line/bets/period=0;chmp=a:10353;', '/su/betting/Football/Turkey/Super+League/', '/sport/futbol/turcija-superliga']},
                {id: '97', urls:['/v3/ru/line/bets/period=0;chmp=a:10353;', '/su/betting/Football/Turkey/1st+League/', '/sport/futbol/turcija-liga-1']},
                {id: '61', urls:['/v3/ru/line/bets/period=0;chmp=a:5367;', '/su/betting/Football/Croatia/1st+League/', '/sport/futbol/khorvatija-liga-1']},
                {id: '109', urls:['/v3/ru/line/bets/period=0;chmp=a:11633;', '/su/betting/Football/Japan/J.League/Division+1/', '/sport/futbol/japonija-j1-liga']},
                {id: '110', urls:['/v3/ru/line/bets/period=0;chmp=a:12201;', '/su/betting/Football/Japan/J.League/Division+2/', '/sport/futbol/japonija-j2-liga']},
                {id: '64', urls:['/v3/ru/line/bets/period=0;chmp=a:16261;', '/su/betting/Football/Bosnia+and+Herzegovina/Premier+League/', '/sport/futbol/bosnija-i-gercegovina-premer-liga']},
                {id: '90', urls:['/v3/ru/line/bets/period=0;chmp=a:9876;', '/su/betting/Football/Chile/Primera+Division/', '/sport/futbol/chili-primera-divizion']},
                {id: '39335r', urls:['/', '/', '/']},
                {id: '15', urls:['/v3/ru/line/bets/period=0;chmp=a:97;', '/su/betting/Football/England/League+1/', '/sport/futbol/anglija-liga-1']},
                {id: '32', urls:['/v3/ru/line/bets/period=0;chmp=a:7859;', '/su/betting/Football/England/League+2/', '/sport/futbol/anglija-liga-2']},
                {id: '22', urls:['/v3/ru/line/bets/period=0;chmp=a:1815;', '/su/betting/Football/Finland/Veikkausliiga/', '/sport/futbol/finljandija-veikkausliiga']},
                {id: '35', urls:['/v3/ru/line/bets/period=0;chmp=a:10565;', '/su/betting/Football/Finland/Ykkonen/', '/sport/futbol/finljandija-ykkonen']},
                {id: '28', urls:['/v3/ru/line/bets/period=0;chmp=a:1222;', '/su/betting/Football/Sweden/Allsvenskan/', '/sport/futbol/shvecija-allsvenskan']},
                {id: '37', urls:['/v3/ru/line/bets/period=0;chmp=a:11445;', '/su/betting/Football/Sweden/Superettan/', '/sport/futbol/shvecija-superettan']},
                {id: '8', urls:['/v3/ru/line/bets/period=0;chmp=a:445;', '/su/betting/Football/England/Premier+League/', '/sport/futbol/anglija-premer-liga']},
                {id: '122', urls:['/v3/ru/line/bets/period=0;chmp=a:11854;', '/su/betting/Football/Russia/FNL/', '/sport/futbol/rossija-fnl']},
                {id: '70', urls:['/v3/ru/line/bets/period=0;chmp=a:24;', '/su/betting/Football/England/Championship/', '/sport/futbol/anglija-chempionship']},
                {id: '440', urls:['/v3/ru/line/bets/period=0;chmp=a:11163;', '/su/betting/Football/Serbia/SuperLiga/', '/sport/futbol/serbija-superliga']},
                {id: '67', urls:['/v3/ru/line/bets/period=0;chmp=a:3807;', '/su/betting/Football/Hungary/NB+I/', '/sport/futbol/vengrija-liga-nb-i']},
                {id: '68', urls:['/v3/ru/line/bets/period=0;chmp=a:55979;', '/su/betting/Football/Hungary/NB+II/', '/sport/futbol/vengrija-liga-nb-ii']},
                {id: '24', urls:['/v3/ru/line/bets/period=0;chmp=a:3507;', '/su/betting/Football/Belgium/1st+Division+A/', '/sport/futbol/belgija-pervyjj-divizion-a']},
                {id: '59', urls:['/v3/ru/line/bets/period=0;chmp=a:8873;', '/su/betting/Football/Bulgaria/1st+League/', '/sport/futbol/bolgarija-gruppa-a']},
                {id: '30', urls:['/v3/ru/line/bets/period=0;chmp=a:1321;', '/su/betting/Football/Denmark/Superliga/', '/sport/futbol/danija-superliga']},
                {id: '39', urls:['/v3/ru/line/bets/period=0;chmp=a:6460;', '/su/betting/Football/Denmark/1st+Division/', '/sport/futbol/danija-pervyjj-divizion']},
                {id: '76', urls:['/v3/ru/line/bets/period=0;chmp=a:11287;', '/su/betting/Football/Iran/Pro+League/', '/sport/futbol/iran-pro-liga']},
                {id: '119', urls:['/v3/ru/line/bets/period=0;chmp=a:5480;', '/su/betting/Football/Poland/Ekstraklasa/', '/sport/futbol/polsha-ekstraklasa']},
                {id: '120', urls:['/v3/ru/line/bets/period=0;chmp=a:12837;', '/su/betting/Football/Poland/I+Liga/', '/sport/futbol/polsha-liga-1']},
                {id: '16', urls:['/v3/ru/line/bets/period=0;chmp=a:433;', '/su/betting/Football/France/Ligue+1/', '/sport/futbol/francija-liga-1']},
                {id: '17', urls:['/v3/ru/line/bets/period=0;chmp=a:432;', '/su/betting/Football/France/Ligue+2/', '/sport/futbol/francija-liga-2']},
                {id: '121', urls:['/v3/ru/line/bets/period=0;chmp=a:74979;', '/su/betting/Football/Russia/Premier+League/', '/sport/futbol/rossija-premer-liga']},
                {id: '49', urls:['/v3/ru/line/bets/period=0;chmp=a:13097;', '/su/betting/Football/Austria/Bundesliga/', '/sport/futbol/avstrija-bundesliga']},
                {id: '66', urls:['/v3/ru/line/bets/period=0;chmp=a:11953;', '/su/betting/Football/Belarus/Vysshaya+League/', '/sport/futbol/belarus-vysshaja-liga']},
                {id: '26', urls:['/v3/ru/line/bets/period=0;chmp=a:1471;', '/su/betting/Football/Brazil/Serie+A/', '/sport/futbol/brazilija-serija-a']},
                {id: '89', urls:['/v3/ru/line/bets/period=0;chmp=a:16500;', '/su/betting/Football/Brazil/Serie+B/', '/sport/futbol/brazilija-serija-v']},
                {id: '629', urls:['/v3/ru/line/bets/period=0;chmp=a:101509;', '/su/betting/Football/Indonesia/Liga+1/', '/sport/futbol/indonezija-chempionat-a']},
                {id: '29', urls:['/v3/ru/line/bets/period=0;chmp=a:2291;', '/su/betting/Football/Norway/Eliteserien/', '/sport/futbol/norvegija-ehlitserija']},
                {id: '36', urls:['/', '/su/betting/Football/Norway/1st+Division/', '/sport/futbol/norvegija-divizion-1']},
                {id: '123', urls:['/v3/ru/line/bets/period=0;chmp=a:2737;', '/su/betting/Football/Slovakia/Fortuna+Liga/', '/sport/futbol/slovakija-superliga']},
                {id: '86', urls:['/v3/ru/line/bets/period=0;chmp=a:3045;', '/su/betting/Football/Slovenia/1st+League/', '/sport/futbol/slovenija-liga-1']},
                {id: '125', urls:['/v3/ru/line/bets/period=0;chmp=a:2737;', '/su/betting/Football/Ukraine/Premier+League/', '/sport/futbol/ukraina-premer-liga']},
                {id: '233', urls:['/v3/ru/line/bets/period=0;chmp=a:15517;', '/su/betting/Football/Ukraine/1st+League/', '/sport/futbol/ukraina-pervaja-liga']},
                {id: '82', urls:['/v3/ru/line/bets/period=0;chmp=a:10298;', '/su/betting/Football/Czech+Republic/1st+League/', '/sport/futbol/chekhija-pervaja-liga']},
                {id: '83', urls:['/v3/ru/line/bets/period=0;chmp=a:10622;', '/su/betting/Football/Czech+Republic/FNL/', '/sport/futbol/chekhija-fnl']},
                {id: '27', urls:['/v3/ru/line/bets/period=0;chmp=a:1266;', '/su/betting/Football/Switzerland/Super+League/', '/sport/futbol/shvejjcarija-superliga']},
                {id: '163', urls:['/v3/ru/line/bets/period=0;chmp=a:11701;', '/su/betting/Football/Venezuela/Primera+Division/', '/sport/futbol/venesuehla-primera-divizion']},
                {id: '9', urls:['/v3/ru/line/bets/period=0;chmp=a:441;', '/su/betting/Football/Germany/Bundesliga/', '/sport/futbol/germanija-bundesliga']},
                {id: '11', urls:['/v3/ru/line/bets/period=0;chmp=a:5;', '/su/betting/Football/Germany/Bundesliga+2/', '/sport/futbol/germanija-bundesliga-2']},
                {id: '622', urls:['/v3/ru/line/bets/period=0;chmp=a:10229;', '/su/betting/Football/Germany/3rd+Liga/', '/sport/futbol/germanija-liga-3']},
                {id: '107', urls:['/v3/ru/line/bets/period=0;chmp=a:392;', '/su/betting/Football/Greece/Super+League/', '/sport/futbol/grecija-superliga']},
                {id: '206', urls:['/v3/ru/line/bets/period=0;chmp=a:11167;', '/su/betting/Football/Egypt/Premier+League/', '/sport/futbol/egipet-premer-liga']},
                {id: '117', urls:['/v3/ru/line/bets/period=0;chmp=a:9077;', '/su/betting/Football/Israel/Premier+League/', '/sport/futbol/izrail-premer-liga']},
                {id: '7', urls:['/v3/ru/line/bets/period=0;chmp=a:75175;', '/su/betting/Football/Spain/Primera+Division/', '/sport/futbol/ispanija-primera']},
                {id: '12', urls:['/v3/ru/line/bets/period=0;chmp=a:341;', '/su/betting/Football/Spain/Segunda+Division/', '/sport/futbol/ispanija-segunda']},
                {id: '13', urls:['/v3/ru/line/bets/period=0;chmp=a:75173;', '/su/betting/Football/Italy/Serie+A/', '/sport/futbol/italija-serija-a']},
                {id: '14', urls:['/v3/ru/line/bets/period=0;chmp=a:45;', '/su/betting/Football/Italy/Serie+B/', '/sport/futbol/italija-serija-v']},
                {id: '215', urls:['/v3/ru/line/bets/period=0;chmp=a:11169;', '/su/betting/Football/Qatar/Stars+League/', '/sport/futbol/katar-starz-liga']},
                {id: '51', urls:['/v3/ru/line/bets/period=0;chmp=a:12079;', '/su/betting/Football/China+PR/Super+League/', '/sport/futbol/kitajj-super-liga']},
                {id: '1', urls:['/v3/ru/line/bets/period=0;chmp=a:15;', '/su/betting/Football/Netherlands/Eredivisie/', '/sport/futbol/niderlandy-eredivisie']},
                {id: '5', urls:['/v3/ru/line/bets/period=0;chmp=a:6315;', '/su/betting/Football/Netherlands/Eerste+Divisie/', '/sport/futbol/niderlandy-pervyjj-divizion']},
                {id: '573', urls:['/v3/ru/line/bets/period=0;chmp=a:14566;', '/', '/']},
                {id: '62', urls:['/v3/ru/line/bets/period=0;chmp=a:60526;', '/', '/sport/futbol/khorvatija-liga-2']},
            ],
            archive: [
                {id: '31'},
                {id: '38'},
                {id: '39336r'},
                {id: '12094s'},
                {id: '12073s'},
                {id: '12284s'},
                {id: '12254s'},
                {id: '12196s'},
                {id: '34146r'},
                {id: '12166s'},
                {id: '12653s'},
                {id: '36638r'},
                {id: '12593s'},
                {id: '12594s'},
                {id: '12612s'},
                {id: '37748r'},
                {id: '12659s'},
                {id: '37192r'},
                {id: '12611s'},
                {id: '12608s'},
            ],
        },
    },
};
