module.exports = {
    urls: [
        {id: '63', urls:['/', '/su/betting/Football/Portugal/Primeira+Liga/', '/sport/futbol/portugalija-primejjra-liga']},
        {id: '100', urls:['/', '/su/betting/Football/Portugal/Segunda+Liga/', '/']},
        {id: '216', urls:['/', '/', '/']},
        {id: '19', urls:['/', '/', '/']},
        {id: '97', urls:['/', '/', '/']},
        {id: '61', urls:['/', '/', '/']},
        {id: '109', urls:['/', '/', '/']},
        {id: '110', urls:['/v3/ru/line/bets/period=0;chmp=a:12201;', '/su/betting/Football/Japan/J.League/Division+2/', '/sport/futbol/japonija-j2-liga']},
        {id: '64', urls:['/', '/', '/']},
        {id: '90', urls:['/', '/', '/']},
        {id: '39335r', urls:['/', '/', '/']},
        {id: '15', urls:['/v3/ru/line/bets/period=0;chmp=a:97;', '/su/betting/Football/England/League+1/', '/sport/futbol/anglija-liga-1']},
        {id: '32', urls:['/v3/ru/line/bets/period=0;chmp=a:7859;', '/su/betting/Football/England/League+2/', '/sport/futbol/anglija-liga-2']},
        {id: '22', urls:['/', '/su/betting/Football/Finland/Veikkausliiga/', '/sport/futbol/finljandija-veikkausliiga']},
        {id: '35', urls:['/', '/su/betting/Football/Finland/Ykkonen/', '/']},
        {id: '28', urls:['/v3/ru/line/bets/period=0;chmp=a:1222;', '/su/betting/Football/Sweden/Allsvenskan/', '/sport/futbol/shvecija-allsvenskan']},
        {id: '37', urls:['/v3/ru/line/bets/period=0;chmp=a:11445;', '/', '/']},
        {id: '8', urls:['/v3/ru/line/bets/period=0;chmp=a:445;', '/su/betting/Football/England/Premier+League/', '/sport/futbol/anglija-premer-liga']},
        {id: '122', urls:['/v3/ru/line/bets/period=0;chmp=a:11854;', '/su/betting/Football/Russia/FNL/', '/sport/futbol/rossija-fnl']},
        {id: '70', urls:['/', '/su/betting/Football/England/Championship/', '/sport/futbol/anglija-chempionship']},
        {id: '440', urls:['/', '/', '/']},
        {id: '67', urls:['/', '/', '/']},
        {id: '68', urls:['/', '/', '/sport/futbol/vengrija-liga-nb-ii']},
        {id: '24', urls:['/v3/ru/line/bets/period=0;chmp=a:3507;', '/', '/']},
        {id: '59', urls:['/', '/', '/']},
        {id: '30', urls:['/v3/ru/line/bets/period=0;chmp=a:1321;', '/su/betting/Football/Denmark/Superliga/', '/sport/futbol/danija-superliga']},
        {id: '39', urls:['/', '/', '/']},
        {id: '76', urls:['/', '/', '/']},
        {id: '119', urls:['/', '/', '/sport/futbol/polsha-ekstraklasa']},
        {id: '120', urls:['/v3/ru/line/bets/period=0;chmp=a:12837;', '/su/betting/Football/Poland/I+Liga/', '/sport/futbol/polsha-liga-1']},
        {id: '16', urls:['/v3/ru/line/bets/period=0;chmp=a:433;', '/su/betting/Football/France/Ligue+1/', '/sport/futbol/francija-liga-1']},
        {id: '17', urls:['/', '/', '/']},
        {id: '121', urls:['/v3/ru/line/bets/period=0;chmp=a:74979;', '/su/betting/Football/Russia/Premier+League/', '/sport/futbol/rossija-premer-liga']},
        {id: '49', urls:['/', '/', '/']},
        {id: '66', urls:['/', '/', '/']},
        {id: '26', urls:['/', '/su/betting/Football/Brazil/Serie+A/', '/']},
        {id: '89', urls:['/v3/ru/line/bets/period=0;chmp=a:16500;', '/su/betting/Football/Brazil/Serie+B/', '/sport/futbol/brazilija-serija-v']},
        {id: '629', urls:['/', '/', '/']},
        {id: '29', urls:['/', '/su/betting/Football/Norway/Eliteserien/', '/sport/futbol/norvegija-ehlitserija']},
        {id: '36', urls:['/', '/', '/']},
        {id: '123', urls:['/', '/', '/']},
        {id: '86', urls:['/', '/', '/']},
        {id: '125', urls:['/', '/', '/']},
        {id: '233', urls:['/', '/', '/']},
        {id: '82', urls:['/v3/ru/line/bets/period=0;chmp=a:10298;', '/', '/']},
        {id: '83', urls:['/', '/', '/']},
        {id: '27', urls:['/', '/', '/']},
        {id: '163', urls:['/v3/ru/line/bets/period=0;chmp=a:11701;', '/su/betting/Football/Venezuela/Primera+Division/', '/sport/futbol/venesuehla-primera-divizion']},
        {id: '9', urls:['/v3/ru/line/bets/period=0;chmp=a:441;', '/su/betting/Football/Germany/Bundesliga/', '/sport/futbol/germanija-bundesliga']},
        {id: '11', urls:['/v3/ru/line/bets/period=0;chmp=a:5;', '/', '/sport/futbol/germanija-bundesliga-2']},
        {id: '622', urls:['/', '/', '/']},
        {id: '107', urls:['/', '/', '/']},
        {id: '206', urls:['/', '/', '/']},
        {id: '117', urls:['/', '/', '/']},
        {id: '7', urls:['/v3/ru/line/bets/period=0;chmp=a:75175;', '/su/betting/Football/Spain/Primera+Division/', '/sport/futbol/ispanija-primera']},
        {id: '12', urls:['/', '/su/betting/Football/Spain/Segunda+Division/', '/sport/futbol/ispanija-segunda']},
        {id: '13', urls:['/v3/ru/line/bets/period=0;chmp=a:75173;', '/su/betting/Football/Italy/Serie+A/', '/sport/futbol/italija-serija-a']},
        {id: '14', urls:['/v3/ru/line/bets/period=0;chmp=a:45;', '/su/betting/Football/Italy/Serie+B/', '/sport/futbol/italija-serija-v']},
        {id: '215', urls:['/', '/', '/']},
        {id: '51', urls:['/', '/', '/']},
        {id: '1', urls:['/v3/ru/line/bets/period=0;chmp=a:15;', '/', '/sport/futbol/niderlandy-eredivisie']},
        {id: '5', urls:['/v3/ru/line/bets/period=0;chmp=a:6315;', '/su/betting/Football/Netherlands/Eerste+Divisie/', '/sport/futbol/niderlandy-pervyjj-divizion']},
        {id: '573', urls:['/v3/ru/line/bets/period=0;chmp=a:14566;', '/', '/']},
    ],
    archive: [
        {id: '31'},
        {id: '38'},
        {id: '39336r'},
    ]
};
